### ISSUE TITLE
Expose default_display_matches_hook

### ISSUE THREAD

**Issue by asmeurer** [stefanholek/rl#8]
I'm trying to write a custom display matches hook, but I'm having a hard time. Basically, I can't get the redisplay(force=True) to work. 

I looked at the default implementation, `default_display_matches_hook`, and it looks like it is doing some other stuff like clearing control-C, which I would have never even thought of. It would be nice if this function were exposed to the Python API. 

Basically, all I want to do with my custom hook is to change what matches are displayed (or, more precisely, to remove a common prefix from each match, so that they aren't so long). In theory, this is as simple as creating a hook that modifies the matches list, subtracts an amount from the longest match length, calls `display_match_list`, and then calls `redisplay(force=True)`, but as I noted, it doesn't work.

**Comment by stefanholek** [comment]
FTR: Readline's code does indeed not match the docs. Query-items 0 should not prompt. Fixed in rl 3.0.

https://github.com/stefanholek/rl/blob/master/rl/examples/display_matches_hook.py
