### ISSUE TITLE
License

### ISSUE THREAD

**Issue by asmeurer** [stefanholek/rl#9]
What exactly is the license of this code? The only reference I could find was the trove classifiers in setup.py, which list both GPL and PSF. Is it either or, or are some parts GPL and some parts PSF?  Whatever it is, it would help if there were a LICENSE file that explained it.

**Comment by gyehuda** [comment]
@stefanholek can you clarify: is this code a derivative work based on an existing GPL-licensed project? 

If so I believe @asmeurer is correct that 1. you must provide a LICENSE file and 2. that license must be GPL and cannot be PSF.  Thanks.

**Comment by stefanholek** [comment]
rl 3.0 is now GPLv3 only.
